spring:
  cloud:
    config:
      # 对应分支
      label: master
      server:
        git:
          # git地址
          uri: ssh://git@git.zhanhaijingji.cn:2222/zhanhai/profile.git
          # 远程目录
          search-paths: zhangshang
          ignoreLocalSshSettings: true
          # 私钥
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEowIBAAKCAQEAovVc6pSyNd8uagEH+dRq04JQ/99KG4QIxuNpgnpioIuUTxmy
            MKUj+srNktscai0hH36c1WxzTXB/6M5wJZ/iSfKL8EAwKsyD9bwzmRVsviJrH4ZW
            NKwgL+6HXuJoWDrSGa9ynB2bV5RzYAAwvzu9nEW7NwRmkeDHuiMXQ3Bb8bBf7ucX
            VHY1L1V5Nyu1tVIq+2537Vbab9DsE/wEwZWXrqArZSNNxINXYK4sU/1FPQu0QxNZ
            5144OrL1nQx23kciw2bBBVyv0Uy3NkdMYQFoMOuHCwDWTYt+Zy3lr+sLFvTLzRbv
            8b2awZ2O3/bFipMkEJ831faHGZri0oVF9MUTtwIDAQABAoIBAGPX5bgspwvu1GdK
            fnKJvXIeFDbRvnwhZ6dESq8RAUDQhGv6mHzJkcPlYhMqgLxlLjg3wSvaqMK3vQcN
            BRVoYqNgInFvQpPWfrufNhYDVH8iY3QLQOJA2+/CO9rc6YW1dGkcYCJa2YTNhes5
            8qQYnFIVP2G0JowWpwja2zQMsajgp3xOGF9NNIrOm+Rmc4gghp1D2SVLtd3imvCl
            9k4unySaQyheEsnjCFfWHqkiRd0CtXT6sdJsCd2qtyMBCaZ+FAb3NBNKlGYku6jA
            LQHLMEs/XDDub6yq7w00fO1q6AO8Qu8acDmFUx49rxQyJv5mW2g1Lp0eDeJpi57N
            nTMPvwECgYEAzWLmopnIJH7XZbpokCsaUUKF/GMnPaXnp9WcIgOcAOWPyARY3cht
            yQU2bobjGcMgzd9qW46DxF3fTIZzBKJmFuE6ILTw12gDi3521Mbl6Zc5hdLs6hK5
            pgVjTufB2cRWQ986ywsqx65ejQQ+YAWBKLlbBS4cZFjZWsioIDqhiEECgYEAyx3W
            K22XNCzU/p7UnaZYp2IPCei9w9JjNgS1jZCqQdS/ZVz7r9QpiQjdSVbRn6D7kz4b
            lLLc5iAYzbXvA252s1WjglIjcpp4u6DJiEE+vMvpHiYlYz1dsvHHDl+Nsu5/U0JZ
            +XIilkGQp9myo2jBLjaiEJiZBfIXx0FcVnGrXfcCgYA7oCS4u9Bg1/oMbGuCvyCq
            ypc/SEHSIeH41Yi4TzfxArQVKz3pVRCaNUsyFzLC/eT+H4gvAFa8oUv8WWP2yna8
            2bIYYK8yud2dl59D8mI4yFBIy40//yOqURIdjCa448jvd1UIMTvAMJz+b2b0VWTD
            v9vuyw4vC6Q+ONamVJ8kgQKBgBaE7lPOSK9OMScxsNzxrm6QXp54oWFul/VLPF2/
            pkC6N6YjUvxBh4Fb7DzPVVpfXMUMY75uvjL9aAKWozM8Mgjb+87dEHUKT0xuHSnw
            IeaIrQXcsNR530ORrsIXMfyemJtAhf0z/EWwaztQ1Y9sc86N3BX+9ShFmQFMa9Jh
            s+AtAoGBAKTwUInlZABc5dCMRFbkK4uuM062uWRsKxQlVufpwkHDuqb58ti90Add
            8x+GfHy6NiD6Lfl4mO46QBksq0GBsTUpZvuzgKe6yTQs8vqDuU1tOK78qUy7cYC9
            GcPPxDMJ2ixd+3icwYvax+w8ib46XdQQe9E95DwMUyUNLT3pwk4t
            -----END RSA PRIVATE KEY-----

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka,http://eureka2:8761/eureka