server:
  port: 8961

spring:
  redis:
    host: 172.16.246.128
    port: 6379
    password: 123456
    database: 6
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: lb://boot-hello-service
          order: 0
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback #熔断后访问路径
        filters:
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@ipKeyResolver}'
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 #熔断超时时间


eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.246.128:8761/eureka,http://172.16.246.128:8762/eureka