spring:
  redis:
    host: 172.16.246.128
    port: 6379
    password: 123456
    database: 6

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://172.16.246.128:8761/eureka,http://172.16.246.128:8762/eureka